export const ADD_BOOKS = 'ADD_BOOKS';
export const DELETE_BOOK = 'DELETE_BOOK';
export const DELETE_ALL_BOOKS = 'DELETE_ALL_BOOKS';

export const FETCH_BOOK_LOADING = 'FETCH_BOOK_LOADING';
export const FETCH_BOOK_SUCCESS = 'FETCH_BOOK_SUCCESS';
export const FETCH_BOOK_ERROR = 'FETCH_BOOK_ERROR';
